import sys
from pathlib import Path
from typing import List
from math import floor
import numpy  as np
sys.path.append(str(Path(__file__).parent.parent))

from utils.txt_to_list_reader import txt_to_list_reader

def get_area(red_tiles):
    n = len(red_tiles)
    for i in range(n):
        tile  = red_tiles[i]
        split_str = tile.split(",")
        red_tiles[i] = (int(split_str[0]),int(split_str[1]))
    
    largest_area = 0
    generating_pair = ()
    for i in range(n):
        for j in range(i+1,n):
            if i!=j:
                dx = abs(red_tiles[i][0]-red_tiles[j][0])+1 
                dy = abs(red_tiles[i][1]-red_tiles[j][1])+1
                area = dx*dy
                if area > largest_area:
                    largest_area =  area
                    generating_pair = (red_tiles[i],red_tiles[j])

    print(f"Larges area: {largest_area}")
    print(f"Generated by: {generating_pair}")



if __name__ == "__main__":
    red_tiles =  txt_to_list_reader("problem-9/real-input.txt")
    get_area(red_tiles)